let listBooks = [
    {
        id: 1,
        isbn : 345522,
        title: 'Belajar Coding',
        author: 'John Doe',
        year: 2020,
        genre: 'Programming',
        publisher: 'Tech Books',
    },
    {
        id: 2,
        isbn : 123456,
        title: 'JavaScript untuk Pemula',
        author: 'Jane Smith',
        year: 2021,
        genre: 'Programming',
        publisher: 'Code Academy',
    },
    {
        id: 3,
        isbn : 789101,
        title: 'How to Public Speaking',
        author: 'Alice Johnson',
        year: 2018,
        genre: 'Self Development',
        publisher: 'Awesome Reads',
    },
    {
        id: 4,
        isbn : 112131,
        title: 'Belajar Mengatur Keuangan',
        author: 'David Brown',
        year: 2015,
        genre: 'Programming ',
        publisher: 'moneywise',
    },
    {
        id: 5,
        isbn : 342765,
        title: 'Time Management Is a Key',
        author: 'Stefen John D.',
        year: 2011,
        genre: 'Self Development',
        publisher: 'Inc. Corporation',
    },
    {
        id: 6,
        isbn : 901298,
        title: 'How to use AI Correctly',
        author: 'Kenneth',
        year: 1995,
        genre: 'Programming',
        publisher: 'Xavierius Group',
    },
    {
        id: 7,
        isbn : 654321,
        title: 'Seporsi Mie Ayam Sebelum Kuliah',
        author: 'Brian Khrisna',
        year: 2017,
        genre: 'Novel',
        publisher: 'Gramedia',
    }
];
export default listBooks;         